server:
  port: 9201

spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: demo1
          uri: lb://demo1
          predicates:
            - Path=/demo1/**
        - id: demo2
          uri: lb://demo2
          predicates:
            - Path=/demo2/**

management:
  endpoint:
    gateway:
      enabled: true

